@echo off
copy SprintIntoBattle.lua BarbaricRage.lua
copy SprintIntoBattle.lua BattleReprieve.lua
copy SprintIntoBattle.lua Blizzard.lua
copy SprintIntoBattle.lua Brewmaster.lua
copy SprintIntoBattle.lua DefenderofEverfrost.lua
copy SprintIntoBattle.lua HalasianAuthority.lua
copy SprintIntoBattle.lua Herbology.lua
copy SprintIntoBattle.lua WarWounds.lua
copy SprintIntoBattle.lua SummonHalasianBrew.lua
copy SprintIntoBattle.lua FaydarksChampion.lua
copy SprintIntoBattle.lua FueledByHate.lua
copy SprintIntoBattle.lua FuryofInnoruuk.lua
copy SprintIntoBattle.lua HatefulMind.lua
copy SprintIntoBattle.lua Hover.lua
copy SprintIntoBattle.lua InnoruuksGift.lua
copy SprintIntoBattle.lua MasteroftheShadows.lua
copy SprintIntoBattle.lua PoisonCrafter.lua
copy SprintIntoBattle.lua PoisonExpertise.lua
copy SprintIntoBattle.lua PursuitoftheArcane.lua
copy SprintIntoBattle.lua TheFocisMagicalProtection.lua
copy SprintIntoBattle.lua AggressiveStrike.lua
copy SprintIntoBattle.lua BodybyButcherblock.lua
copy SprintIntoBattle.lua DefenderofKaladim.lua
copy SprintIntoBattle.lua DwarvenFortitude.lua
copy SprintIntoBattle.lua MasteroftheTumpyTonic.lua
copy SprintIntoBattle.lua MiningExpertise.lua
copy SprintIntoBattle.lua RushintoBattle.lua
copy SprintIntoBattle.lua StrongHeart.lua
copy SprintIntoBattle.lua WeaponForger.lua
copy SprintIntoBattle.lua ArcofLightning.lua
copy SprintIntoBattle.lua CastingFury.lua
copy SprintIntoBattle.lua Chemist.lua
copy SprintIntoBattle.lua ClearMind.lua
copy SprintIntoBattle.lua ErudsTeachings.lua
copy SprintIntoBattle.lua FallingGrace.lua
copy SprintIntoBattle.lua IntellectoftheSage.lua
copy SprintIntoBattle.lua IntellectualFeasting.lua
copy SprintIntoBattle.lua MagicalProtection.lua
copy SprintIntoBattle.lua WardofGlyphs.lua
copy SprintIntoBattle.lua AkanonsInnovation.lua
copy SprintIntoBattle.lua ChemicalCalculations.lua
copy SprintIntoBattle.lua ClockworkArmy.lua
copy SprintIntoBattle.lua FlashofInsight.lua
copy SprintIntoBattle.lua ForgeInvention.lua
copy SprintIntoBattle.lua HealthyAppetite.lua
copy SprintIntoBattle.lua IllusionClockwork.lua
copy SprintIntoBattle.lua LostintheCrowd.lua
copy SprintIntoBattle.lua MeldrathsTeachings.lua
copy SprintIntoBattle.lua SteamfontsMagicalBarrier.lua
copy SprintIntoBattle.lua Ayr`DalAdornment.lua
copy SprintIntoBattle.lua Camouflage.lua
copy SprintIntoBattle.lua ElvenHeritage.lua
copy SprintIntoBattle.lua ElvenReflexes.lua
copy SprintIntoBattle.lua ForestNavigation.lua
copy SprintIntoBattle.lua GiftoftheFaydark.lua
copy SprintIntoBattle.lua Hardiness.lua
copy SprintIntoBattle.lua MisfitsTrickery.lua
copy SprintIntoBattle.lua MixedKnowledge.lua
copy SprintIntoBattle.lua RebelliousSpirit.lua
copy SprintIntoBattle.lua TendWounds.lua
copy SprintIntoBattle.lua AHalflingsFeast.lua
copy SprintIntoBattle.lua ArcaneKnowledge.lua
copy SprintIntoBattle.lua ConnoisseurofFineWines.lua
copy SprintIntoBattle.lua ElvenWisdom.lua
copy SprintIntoBattle.lua EsotericStudy.lua
copy SprintIntoBattle.lua FuryofFelwithe.lua
copy SprintIntoBattle.lua GildingofFelwithe.lua
copy SprintIntoBattle.lua GracefulMovements.lua
copy SprintIntoBattle.lua HarmoniousMind.lua
copy SprintIntoBattle.lua IntricateCreations.lua
copy SprintIntoBattle.lua TenetofTakish`Hiz.lua
copy SprintIntoBattle.lua TrainingoftheKoada`Dal.lua
copy SprintIntoBattle.lua Clothier.lua
copy SprintIntoBattle.lua Diplomacy.lua
copy SprintIntoBattle.lua Diversity.lua
copy SprintIntoBattle.lua EnvironmentalAdaptability.lua
copy SprintIntoBattle.lua Multitalented.lua
copy SprintIntoBattle.lua Perserverance.lua
copy SprintIntoBattle.lua UrbanSprawl.lua
copy SprintIntoBattle.lua Versatility.lua
copy SprintIntoBattle.lua WilltoSurvive.lua
copy SprintIntoBattle.lua DefensiveColoration.lua
copy SprintIntoBattle.lua ProficientSwimmer.lua
copy SprintIntoBattle.lua ReptilianAncestry.lua
copy SprintIntoBattle.lua ArmoroftheFeerrott.lua
copy SprintIntoBattle.lua BattleRest.lua
copy SprintIntoBattle.lua BruteStrength.lua
copy SprintIntoBattle.lua ImpenetrableWill.lua
copy SprintIntoBattle.lua ManyMarches.lua
copy SprintIntoBattle.lua OggokianAggression.lua
copy SprintIntoBattle.lua OggokianTrade.lua
copy SprintIntoBattle.lua RallosZeksBlessing.lua
copy SprintIntoBattle.lua RallosianReadiness.lua
copy SprintIntoBattle.lua RockThrower.lua
copy SprintIntoBattle.lua ShoulderSlam.lua
copy SprintIntoBattle.lua Antidote.lua
copy SprintIntoBattle.lua DarkAgenda.lua
copy SprintIntoBattle.lua InstrumentsoftheUnderfoot.lua
copy SprintIntoBattle.lua PitifulPlea.lua
copy SprintIntoBattle.lua PoisonPlay.lua
copy SprintIntoBattle.lua RodentReflexes.lua
copy SprintIntoBattle.lua ShadowLurker.lua
copy SprintIntoBattle.lua SoulMending.lua
copy SprintIntoBattle.lua StreetThug.lua
copy SprintIntoBattle.lua BogBully.lua
copy SprintIntoBattle.lua CazicThulesGift.lua
copy SprintIntoBattle.lua GiftoftheInnothule.lua
copy SprintIntoBattle.lua InnothulesBlessing.lua
copy SprintIntoBattle.lua ManiacalMadness.lua
copy SprintIntoBattle.lua MenderoftheMire.lua
copy SprintIntoBattle.lua SummonFilthyWater.lua
copy SprintIntoBattle.lua SwampBreath.lua
copy SprintIntoBattle.lua TastyThings.lua
copy SprintIntoBattle.lua ThulesGuidance.lua
copy SprintIntoBattle.lua TrollGourmet.lua
copy SprintIntoBattle.lua Camo.lua
copy SprintIntoBattle.lua ElvishSpirits.lua
copy SprintIntoBattle.lua FaydwerFashions.lua
copy SprintIntoBattle.lua ForestFire.lua
copy SprintIntoBattle.lua KeeperoftheForest.lua
copy SprintIntoBattle.lua LightFooted.lua
copy SprintIntoBattle.lua NaturalRecovery.lua
copy SprintIntoBattle.lua ShieldofNature.lua
copy SprintIntoBattle.lua VitalityoftheFier`Dal.lua
copy SprintIntoBattle.lua WisdomoftheFaydark.lua
copy SprintIntoBattle.lua AerialDodging.lua
copy SprintIntoBattle.lua EscapingDive.lua
copy SprintIntoBattle.lua FaeDexterity.lua
copy SprintIntoBattle.lua FaeFlight.lua
copy SprintIntoBattle.lua Featherfall.lua
copy SprintIntoBattle.lua ForestKnowledge.lua
copy SprintIntoBattle.lua Glide.lua
copy SprintIntoBattle.lua MagicoftheFae.lua
copy SprintIntoBattle.lua MagicalTeachings.lua
copy SprintIntoBattle.lua ToxicProtection.lua
copy SprintIntoBattle.lua WindWalker.lua
copy SprintIntoBattle.lua AerialDodging.lua
copy SprintIntoBattle.lua ArasaiFlight.lua
copy SprintIntoBattle.lua ArasaiSavvy.lua
copy SprintIntoBattle.lua ArasaisEndurance.lua
copy SprintIntoBattle.lua DarkEnvy.lua
copy SprintIntoBattle.lua MagicProtection.lua
copy SprintIntoBattle.lua NeriakPrecision.lua
copy SprintIntoBattle.lua Transmography.lua
copy SprintIntoBattle.lua CarpentersTouch.lua
copy SprintIntoBattle.lua HerbalSupplementation.lua
copy SprintIntoBattle.lua HuntersFury.lua
copy SprintIntoBattle.lua Junglewalk.lua
copy SprintIntoBattle.lua ReflexiveLanding.lua
copy SprintIntoBattle.lua Spirituality.lua
copy SprintIntoBattle.lua Stride.lua
copy SprintIntoBattle.lua WeaponProduction.lua
