/*  
    EQ2Emulator:  Everquest II Server Emulator
    Copyright (C) 2007  EQ2EMulator Development Team (http://www.eq2emulator.net)

    This file is part of EQ2Emulator.

    EQ2Emulator is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    EQ2Emulator is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with EQ2Emulator.  If not, see <http://www.gnu.org/licenses/>.
*/


#define ITEM_STAT_VS_PHYSICAL			200
#define ITEM_STAT_VS_ELEMENTAL			201
#define ITEM_STAT_VS_NOXIOUS			202
#define ITEM_STAT_VS_ARCANE				203



#define ITEM_STAT_DMG_SLASH				300
#define ITEM_STAT_DMG_CRUSH				301
#define ITEM_STAT_DMG_PIERCE			302
#define ITEM_STAT_DMG_HEAT				303
#define ITEM_STAT_DMG_COLD 				304
#define ITEM_STAT_DMG_MAGIC				305
#define ITEM_STAT_DMG_MENTAL			306
#define ITEM_STAT_DMG_DIVINE			307
#define ITEM_STAT_DMG_DISEASE			308
#define ITEM_STAT_DMG_POISON			309
#define ITEM_STAT_DMG_DROWNING			310
#define ITEM_STAT_DMG_FALLING			311
#define ITEM_STAT_DMG_PAIN				312
#define ITEM_STAT_DMG_MELEE				313


#define ITEM_STAT_HEALTH				500
#define ITEM_STAT_POWER					501
#define ITEM_STAT_CONCENTRATION			502
#define ITEM_STAT_SAVAGERY				503


#define ITEM_STAT_HPREGEN				600
#define ITEM_STAT_MANAREGEN				601
#define ITEM_STAT_HPREGENPPT			602
#define ITEM_STAT_MPREGENPPT			603
#define ITEM_STAT_COMBATHPREGENPPT		604
#define ITEM_STAT_COMBATMPREGENPPT		605
#define ITEM_STAT_MAXHP					606
#define ITEM_STAT_MAXHPPERC				607
#define ITEM_STAT_MAXHPPERCFINAL		608
#define ITEM_STAT_SPEED					609
#define ITEM_STAT_SLOW					610
#define ITEM_STAT_MOUNTSPEED			611
#define ITEM_STAT_MOUNTAIRSPEED			612
#define ITEM_STAT_LEAPSPEED				613
#define ITEM_STAT_LEAPTIME				614
#define ITEM_STAT_GLIDEEFFICIENCY		615
#define ITEM_STAT_OFFENSIVESPEED		616
#define ITEM_STAT_ATTACKSPEED			617
#define ITEM_STAT_SPELLWEAPONATTACKSPEED 618
#define ITEM_STAT_MAXMANA				619
#define ITEM_STAT_MAXMANAPERC			620
#define ITEM_STAT_MAXATTPERC			621
#define ITEM_STAT_BLURVISION			622
#define ITEM_STAT_MAGICLEVELIMMUNITY	623
#define ITEM_STAT_HATEGAINMOD			624
#define ITEM_STAT_COMBATEXPMOD			625
#define ITEM_STAT_TRADESKILLEXPMOD		626
#define ITEM_STAT_ACHIEVEMENTEXPMOD		627
#define ITEM_STAT_SIZEMOD				628
#define ITEM_STAT_DPS					629
#define ITEM_STAT_SPELLWEAPONDPS		630
#define ITEM_STAT_STEALTH				631
#define ITEM_STAT_INVIS					632
#define ITEM_STAT_SEESTEALTH			633
#define ITEM_STAT_SEEINVIS				634
#define ITEM_STAT_EFFECTIVELEVELMOD		635
#define ITEM_STAT_RIPOSTECHANCE			636
#define ITEM_STAT_PARRYCHANCE			637
#define ITEM_STAT_DODGECHANCE			638
#define ITEM_STAT_AEAUTOATTACKCHANCE	639
#define ITEM_STAT_SPELLWEAPONAEAUTOATTACKCHANCE		640
#define ITEM_STAT_DOUBLEATTACKCHANCE				641
#define ITEM_STAT_PVPDOUBLEATTACKCHANCE				642
#define ITEM_STAT_SPELLWEAPONAEAUTOATTACKCHANCE		643
#define ITEM_STAT_PVPSPELLWEAPONDOUBLEATTACKCHANCE  644
#define ITEM_STAT_SPELLDOUBLEATTACKCHANCE			645
#define ITEM_STAT_PVPSPELLDOUBLEATTACKCHANCE		646
#define ITEM_STAT_FLURRY					647
#define ITEM_STAT_SPELLWEAPONFLURRY			648
#define ITEM_STAT_MELEEDAMAGEMULTIPLIER		649
#define ITEM_STAT_EXTRAHARVESTCHANCE		650
#define ITEM_STAT_EXTRASHIELDBLOCKCHANCE	651
#define ITEM_STAT_ITEMHPREGENPPT	  		652
#define ITEM_STAT_ITEMPPREGENPPT			653
#define ITEM_STAT_MELEECRITCHANCE			654
#define ITEM_STAT_CRITAVOIDANCE				655
#define ITEM_STAT_BENEFICIALCRITCHANCE		656
#define ITEM_STAT_CRITBONUS					657
#define ITEM_STAT_PVPCRITBONUS				658
#define ITEM_STAT_BASEMODIFIER				659
#define ITEM_STAT_PVPBASEMODIFIER			660
#define ITEM_STAT_UNCONSCIOUSHPMOD			661
#define ITEM_STAT_SPELLTIMEREUSEPCT			662
#define ITEM_STAT_SPELLTIMERECOVERYPCT		663
#define ITEM_STAT_SPELLTIMECASTPCT			664
#define ITEM_STAT_SPELLTIMEREUSESPELLONLY	665
#define ITEM_STAT_MELEEWEAPONRANGE			666
#define ITEM_STAT_RANGEDWEAPONRANGE			667
#define ITEM_STAT_FALLINGDAMAGEREDUCTION	668
#define ITEM_STAT_RIPOSTEDAMAGE				669
#define ITEM_STAT_MINIMUMDEFLECTIONCHANCE	670
#define ITEM_STAT_MOVEMENTWEAVE				671
#define ITEM_STAT_COMBATHPREGEN				672
#define ITEM_STAT_COMBATMANAREGEN			673
#define ITEM_STAT_CONTESTSPEEDBOOST			674
#define ITEM_STAT_TRACKINGAVOIDANCE			675
#define ITEM_STAT_STEALTHINVISSPEEDMOD		676
#define ITEM_STAT_LOOT_COIN					677
#define ITEM_STAT_ARMORMITIGATIONINCREASE   678
#define ITEM_STAT_AMMOCONSERVATION			679
#define ITEM_STAT_STRIKETHROUGH				680
#define ITEM_STAT_STATUSBONUS				681
#define ITEM_STAT_ACCURACY					682
#define ITEM_STAT_COUNTERSTRIKE				683
#define ITEM_STAT_SHIELDBASH				684
#define ITEM_STAT_WEAPONDAMAGEBONUS			685
#define ITEM_STAT_WEAPONDAMAGEBONUSMELEEONLY  686
#define ITEM_STAT_ADDITIONALRIPOSTECHANCE     687
#define ITEM_STAT_CRITICALMITIGATION		688
#define ITEM_STAT_PVPTOUGHNESS				689
#define ITEM_STAT_PVPLETHALITY				690
#define ITEM_STAT_STAMINABONUS				691
#define ITEM_STAT_WISDOMMITBONUS			692
#define ITEM_STAT_HEALRECEIVE				693
#define ITEM_STAT_HEALRECEIVEPERC			694
#define ITEM_STAT_PVPCRITICALMITIGATION		695
#define ITEM_STAT_BASEAVOIDANCEBONUS		696
#define ITEM_STAT_INCOMBATSAVAGERYREGEN		697
#define ITEM_STAT_OUTOFCOMBATSAVAGERYREGEN  698
#define ITEM_STAT_SAVAGERYREGEN				699
#define ITEM_STAT_SAVAGERYGAINMOD			6100
#define ITEM_STAT_MAXSAVAGERYLEVEL			6101

#define ITEM_STAT_SPELL_DAMAGE				700
#define ITEM_STAT_HEAL_AMOUNT				701
#define ITEM_STAT_SPELL_AND_HEAL			702
#define ITEM_STAT_COMBAT_ART_DAMAGE			703
#define ITEM_STAT_SPELL_AND_COMBAT_ART_DAMAGE	704
#define ITEM_STAT_TAUNT_AMOUNT					705
#define ITEM_STAT_TAUNT_AND_COMBAT_ART_DAMAGE	706
#define ITEM_STAT_ABILITY_MODIFIER				707



