/*  
    EQ2Emulator:  Everquest II Server Emulator
    Copyright (C) 2007  EQ2EMulator Development Team (http://www.eq2emulator.net)

    This file is part of EQ2Emulator.

    EQ2Emulator is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    EQ2Emulator is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with EQ2Emulator.  If not, see <http://www.gnu.org/licenses/>.
*/


#define DOV_ITEM_STAT_VS_PHYSICAL			200
#define DOV_ITEM_STAT_VS_HEAT				201 //elemental
#define DOV_ITEM_STAT_VS_POISON				202 //noxious
#define DOV_ITEM_STAT_VS_MAGIC				203 //arcane
#define DOV_ITEM_STAT_VS_DROWNING			210
#define DOV_ITEM_STAT_VS_FALLING			211
#define DOV_ITEM_STAT_VS_PAIN				212
#define DOV_ITEM_STAT_VS_MELEE				213

#define DOV_ITEM_STAT_VS_SLASH				204
#define DOV_ITEM_STAT_VS_CRUSH				205
#define DOV_ITEM_STAT_VS_PIERCE				206
//#define ITEM_STAT_VS_HEAT				203 //just so no build error
#define DOV_ITEM_STAT_VS_COLD				207
//#define ITEM_STAT_VS_MAGIC			205 //just so no build error
#define DOV_ITEM_STAT_VS_MENTAL				208
#define DOV_ITEM_STAT_VS_DIVINE				209
#define DOV_ITEM_STAT_VS_DISEASE			214
//#define ITEM_STAT_VS_POISON			209 //just so no build error
//#define ITEM_STAT_VS_DROWNING			210 //just so no build error
//#define ITEM_STAT_VS_FALLING			211 //just so no build error
//#define ITEM_STAT_VS_PAIN				212 //just so no build error
//#define ITEM_STAT_VS_MELEE			213 //just so no build error

#define DOV_ITEM_STAT_DMG_SLASH				300
#define DOV_ITEM_STAT_DMG_CRUSH				301
#define DOV_ITEM_STAT_DMG_PIERCE			302
#define DOV_ITEM_STAT_DMG_HEAT				303
#define DOV_ITEM_STAT_DMG_COLD 				304
#define DOV_ITEM_STAT_DMG_MAGIC				305
#define DOV_ITEM_STAT_DMG_MENTAL			306
#define DOV_ITEM_STAT_DMG_DIVINE			307
#define DOV_ITEM_STAT_DMG_DISEASE			308
#define DOV_ITEM_STAT_DMG_POISON			309
#define DOV_ITEM_STAT_DMG_DROWNING			310
#define DOV_ITEM_STAT_DMG_FALLING			311
#define DOV_ITEM_STAT_DMG_PAIN				312
#define DOV_ITEM_STAT_DMG_MELEE				313

#define DOV_ITEM_STAT_HEALTH				500
#define DOV_ITEM_STAT_POWER					501
#define DOV_ITEM_STAT_CONCENTRATION			502

#define DOV_ITEM_STAT_HPREGEN 				600
#define DOV_ITEM_STAT_MANAREGEN 			601
#define DOV_ITEM_STAT_HPREGENPPT 			602
#define DOV_ITEM_STAT_MPREGENPPT 			603
#define DOV_ITEM_STAT_COMBATHPREGENPPT 		604
#define DOV_ITEM_STAT_COMBATMPREGENPPT 		605
#define DOV_ITEM_STAT_MAXHP 				606
#define DOV_ITEM_STAT_MAXHPPERC 			607
#define DOV_ITEM_STAT_SPEED 				608
#define DOV_ITEM_STAT_SLOW 					609
#define DOV_ITEM_STAT_MOUNTSPEED 			610
#define DOV_ITEM_STAT_MOUNTAIRSPEED 		611
#define DOV_ITEM_STAT_OFFENSIVESPEED 		612
#define DOV_ITEM_STAT_ATTACKSPEED 			613
#define DOV_ITEM_STAT_MAXMANA 				614
#define DOV_ITEM_STAT_MAXMANAPERC 			615
#define DOV_ITEM_STAT_MAXATTPERC 			616
#define DOV_ITEM_STAT_BLURVISION 			617
#define DOV_ITEM_STAT_MAGICLEVELIMMUNITY 	618
#define DOV_ITEM_STAT_HATEGAINMOD 			619
#define DOV_ITEM_STAT_COMBATEXPMOD 			620
#define DOV_ITEM_STAT_TRADESKILLEXPMOD 		621
#define DOV_ITEM_STAT_ACHIEVEMENTEXPMOD 	622
#define DOV_ITEM_STAT_SIZEMOD 				623
#define DOV_ITEM_STAT_DPS 					624
#define DOV_ITEM_STAT_STEALTH 				625
#define DOV_ITEM_STAT_INVIS 				626
#define DOV_ITEM_STAT_SEESTEALTH 			627
#define DOV_ITEM_STAT_SEEINVIS 				628
#define DOV_ITEM_STAT_EFFECTIVELEVELMOD 	629
#define DOV_ITEM_STAT_RIPOSTECHANCE 		630
#define DOV_ITEM_STAT_PARRYCHANCE 			631
#define DOV_ITEM_STAT_DODGECHANCE 			632
#define DOV_ITEM_STAT_AEAUTOATTACKCHANCE 	633
#define DOV_ITEM_STAT_MULTIATTACKCHANCE 		634
#define DOV_ITEM_STAT_SPELLMULTIATTACKCHANCE 	635
#define DOV_ITEM_STAT_FLURRY 					636
#define DOV_ITEM_STAT_MELEEDAMAGEMULTIPLIER 	637
#define DOV_ITEM_STAT_EXTRAHARVESTCHANCE 		638
#define DOV_ITEM_STAT_EXTRASHIELDBLOCKCHANCE 	639
#define DOV_ITEM_STAT_ITEMHPREGENPPT 			640
#define DOV_ITEM_STAT_ITEMPPREGENPPT 			641
#define DOV_ITEM_STAT_MELEECRITCHANCE 			642
#define DOV_ITEM_STAT_CRITAVOIDANCE 			643
#define DOV_ITEM_STAT_BENEFICIALCRITCHANCE 		644
#define DOV_ITEM_STAT_CRITBONUS 				645
#define DOV_ITEM_STAT_POTENCY 					646
#define DOV_ITEM_STAT_UNCONSCIOUSHPMOD 			647
#define DOV_ITEM_STAT_ABILITYREUSESPEED 		648
#define DOV_ITEM_STAT_ABILITYRECOVERYSPEED 		649
#define DOV_ITEM_STAT_ABILITYCASTINGSPEED 		650
#define DOV_ITEM_STAT_SPELLREUSESPEED		 	651
#define DOV_ITEM_STAT_MELEEWEAPONRANGE 			652
#define DOV_ITEM_STAT_RANGEDWEAPONRANGE 		653
#define DOV_ITEM_STAT_FALLINGDAMAGEREDUCTION 	654
#define DOV_ITEM_STAT_RIPOSTEDAMAGE 			655
#define DOV_ITEM_STAT_MINIMUMDEFLECTIONCHANCE 	656
#define DOV_ITEM_STAT_MOVEMENTWEAVE 			657
#define DOV_ITEM_STAT_COMBATHPREGEN 			658
#define DOV_ITEM_STAT_COMBATMANAREGEN 			659
#define DOV_ITEM_STAT_CONTESTSPEEDBOOST 		660
#define DOV_ITEM_STAT_TRACKINGAVOIDANCE 		661
#define DOV_ITEM_STAT_STEALTHINVISSPEEDMOD 		662
#define DOV_ITEM_STAT_LOOT_COIN 				663
#define DOV_ITEM_STAT_ARMORMITIGATIONINCREASE 	664
#define DOV_ITEM_STAT_AMMOCONSERVATION 			665
#define DOV_ITEM_STAT_STRIKETHROUGH 			666
#define DOV_ITEM_STAT_STATUSBONUS 				667
#define DOV_ITEM_STAT_ACCURACY 					668
#define DOV_ITEM_STAT_COUNTERSTRIKE 			669
#define DOV_ITEM_STAT_SHIELDBASH 				670
#define DOV_ITEM_STAT_WEAPONDAMAGEBONUS 		671
#define DOV_ITEM_STAT_ADDITIONALRIPOSTECHANCE 	672
#define DOV_ITEM_STAT_CRITICALMITIGATION 		673
#define DOV_ITEM_STAT_PVPTOUGHNESS 				674
#define DOV_ITEM_STAT_STAMINABONUS 				675
#define DOV_ITEM_STAT_WISDOMITBONUS 			676
#define DOV_ITEM_STAT_HEALRECEIVE 				677
#define DOV_ITEM_STAT_HEALRECEIVEPERC 			678
#define DOV_ITEM_STAT_PVPCRITICALMITIGATION		679
#define DOV_ITEM_STAT_BASEAVOIDANCEBONUS 		680




#define DOV_ITEM_STAT_SPELL_DAMAGE			700
#define DOV_ITEM_STAT_HEAL_AMOUNT			701
#define DOV_ITEM_STAT_SPELL_AND_HEAL		702
#define DOV_ITEM_STAT_COMBAT_ART_DAMAGE		703
#define DOV_ITEM_STAT_SPELL_AND_COMBAT_ART_DAMAGE			704
#define DOV_ITEM_STAT_TAUNT_AMOUNT			705
#define DOV_ITEM_STAT_TAUNT_AND_COMBAT_ART_DAMAGE			706
#define DOV_ITEM_STAT_ABILITY_MODIFIER			707



